//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompra
    {
        public int IdDetalleCompra { get; set; }
        public int IdCompra { get; set; }
        public int IdDetalleLote { get; set; }
        public int CantidadCompra { get; set; }
        public decimal PrecioCompra { get; set; }
        public decimal SubtotalCompra { get; set; }
    
        public virtual Compras Compras { get; set; }
        public virtual DetalleLote DetalleLote { get; set; }
    }
}
