//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleVenta()
        {
            this.Devoluciones = new HashSet<Devoluciones>();
        }
    
        public int IdDetalleVenta { get; set; }
        public int IdVenta { get; set; }
        public int IdDetalleLote { get; set; }
        public int CantidadVendida { get; set; }
        public decimal PrecioVenta { get; set; }
        public decimal IVA { get; set; }
        public decimal SubtotalFactura { get; set; }
    
        public virtual DetalleLote DetalleLote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devoluciones> Devoluciones { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
