//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devoluciones
    {
        public int IdDevolución { get; set; }
        public int IdDetalleVenta { get; set; }
        public System.DateTime FechaDevolución { get; set; }
        public int CantidadDevuelta { get; set; }
        public string Motivo { get; set; }
        public decimal TotalDevolución { get; set; }
    
        public virtual DetalleVenta DetalleVenta { get; set; }
    }
}
